### ISSUE TITLE
Error when saving/loading models using save_fit and load_fit functions

### ISSUE THREAD

**Issue by SKMuller** [GWeindel/hmp#122]
When loading a fitted model that has been previously saved with utils.save_fit through the load_fit function, some dimensions seem to be inverted, causing index errors when running other functions. This issue can be circumvented by transposing the appropriate dimensions.
For example:
```
hmp.utils.save_fit(estimates, 'estimates_gamma4_loc6.nc')
estimates = hmp.utils.load_fit('estimates_gamma4_loc6.nc')
estimates['eventprobs'] = estimates.eventprobs.transpose('trial_x_participant','samples','event')
```
Would run without any issues

**Comment by GWeindel** [comment]
This is indeed a bug, possible solutions are to force a certain order of dimension at save or load or to use named dimensions instead of indexes in the affected functions.
Will deal with it in the coming weeks but doesn't seem urgent as there is a workaround
